default: &defaults
   push_api_key: "<%= ENV['APPSIGNAL_PUSH_API_KEY'] %>"
  name: "Expense Tracker"
development:
  <<: *defaults
  active: true
  log_level: true

production:
  <<: *defaults
  active: true
